name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Set up Go 1.14.6
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.6
        id: go

      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Kill Running Process
        run: taskkill /IM "simpleServer.exe" /F
        shell: cmd
        continue-on-error: true

      - name: Build Artifacts
        run: go build -o simpleServer.exe

      - name: Start Process
        run: start ./simpleServer.exe
        shell: cmd
